version: '3'

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: [ '--auth' ]
    restart: always

  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
    ports:
      - 8000:8081
    restart: always
  # node:
  #   container_name: Node-18
  #   depends_on:
  #     - db
  #   image: node:18.15.0-alpine3.17
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   command: npm start
